version: '3.9'

services:
  fastapi:
    build:
      context: .  # Build context is the root of the project
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - postgres  # Make sure Postgres is available
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=epita
      - POSTGRES_USER=amine
      - POSTGRES_PASSWORD=amine

  streamlit:
    build:
      context: .  # The build context for Streamlit
      dockerfile: dockerfile  # Ensure the correct name of the Dockerfile (case-sensitive)
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Mount the entire project directory into /app inside the container
    depends_on:
      - fastapi  # Ensure FastAPI starts before Streamlit
    environment:
      - FASTAPI_PREDICT_URL=http://fastapi:8000/predict/  # Change localhost to service name
      - FASTAPI_PAST_PREDICTIONS_URL=http://fastapi:8000/past_predictions/
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=epita
      - POSTGRES_USER=mohamedaminemrabet
      - POSTGRES_PASSWORD=amine

    networks:
      - my_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mohamedaminemrabet
      POSTGRES_PASSWORD: amine
      POSTGRES_DB: epita
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:  # Persistent volume for Postgres data

networks:
  my_network:
    driver: bridge
