{
 "title": "statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT datasource_name, checkpoint_name, expectation_suite_name FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Num of expectation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(evaluated_expectations) FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last expectations execution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT successful_expectations, unsuccessful_expectations FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "N° of Validated file",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Success percentage per file",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT success_percent, file_name FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Expectation Execution ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(successful_expectations) as successful_expectations, SUM(unsuccessful_expectations) as unsuccessful_expectations FROM prediction_statistics LIMIT 50 "
    }
   ]
  }
 ]
}