{
 "title": "predictions",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Churn by Payment Method",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"PaymentMethod\",\n  COUNT(CASE WHEN CAST(prediction AS numeric) = 1.0 THEN 1 ELSE NULL END) AS churned_customers\nFROM past_predictions\nGROUP BY \"PaymentMethod\"\nORDER BY churned_customers DESC;\n"
    }
   ]
  },
  {
   "title": "Churn Rate by Contract Type",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Contract\",\n  COUNT(CASE WHEN CAST(prediction AS numeric) = 1.0 THEN 1 ELSE NULL END) AS churned_customers\nFROM past_predictions\nGROUP BY \"Contract\"\nORDER BY churned_customers DESC;\n"
    }
   ]
  },
  {
   "title": "Churn by Gender",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"gender\",\n  COUNT(CASE WHEN CAST(prediction AS numeric) = 1.0 THEN 1 ELSE NULL END) AS churned_customers\nFROM past_predictions\nGROUP BY \"gender\"\nORDER BY churned_customers DESC;\n"
    }
   ]
  },
  {
   "title": "Customer Count by Service Subscriptions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"InternetService\",\n  \"PhoneService\",\n  COUNT(\"customerID\") AS customer_count\nFROM past_predictions\nGROUP BY \"InternetService\", \"PhoneService\"\nORDER BY customer_count DESC;\n"
    }
   ]
  }
 ]
}