{
 "title": "statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT datasource_name, checkpoint_name, expectation_suite_name FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  { "title": "Expectations success results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Num of expectation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(evaluated_expectations) FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last expectations execution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT successful_expectations, unsuccessful_expectations FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "N° of Validated file",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Success percentage per file",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT success_percent, file_name FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Expectation Execution ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(successful_expectations) as successful_expectations, SUM(unsuccessful_expectations) as unsuccessful_expectations FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Rows & Columns expectations results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Last Validated Rows",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT nb_valid_rows, nb_invalid_rows FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last Validated columns",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT nb_valid_cols, nb_invalid_cols FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total of Successful validated rows",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(nb_rows) as nb_rows, SUM(nb_valid_rows) as nb_valid_rows FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total of Successful validated columns",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(nb_cols) as nb_cols, SUM(nb_valid_cols) as nb_valid_cols FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total of Unsuccessful validated rows",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(nb_rows) as nb_rows, SUM(nb_invalid_rows) as nb_invalid_rows FROM prediction_statistics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total of Unuccessful validated columns",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(nb_cols) as nb_cols, SUM(nb_invalid_cols) as nb_invalid_cols FROM prediction_statistics LIMIT 50 "
    }
   ]
  }
 ]
}